"""initial_schema

Revision ID: e61a31691c6a
Revises: 
Create Date: 2026-09-29 12:00:54.496887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61a31691c6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('primary_benefit', sa.Text(), nullable=True),
    sa.Column('stipend_reward', sa.Text(), nullable=True),
    sa.Column('eligibility_summary', sa.Text(), nullable=True),
    sa.Column('application_url', sa.String(length=512), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_education_code', sa.String(length=50), nullable=True),
    sa.Column('max_income_annual', sa.Integer(), nullable=True),
    sa.Column('requires_rural', sa.Boolean(), nullable=True),
    sa.Column('applicable_categories', sa.JSON(), nullable=True),
    sa.Column('applicable_states', sa.JSON(), nullable=True),
    sa.Column('eligible_livelihood_goals', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_schemes_is_active'), 'government_schemes', ['is_active'], unique=False)
    op.create_index(op.f('ix_government_schemes_scheme_code'), 'government_schemes', ['scheme_code'], unique=True)
    op.create_table('qualification_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qp_code', sa.String(length=50), nullable=False),
    sa.Column('qualification_name', sa.String(length=255), nullable=False),
    sa.Column('nsqf_level', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=150), nullable=False),
    sa.Column('council', sa.String(length=255), nullable=True),
    sa.Column('min_education', sa.String(length=100), nullable=True),
    sa.Column('preferred_education', sa.String(length=100), nullable=True),
    sa.Column('min_experience_years', sa.Float(), nullable=True),
    sa.Column('training_duration_hours', sa.Integer(), nullable=True),
    sa.Column('official_scheme', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('competencies', sa.JSON(), nullable=True),
    sa.Column('employment_pathways', sa.JSON(), nullable=True),
    sa.Column('self_employment_pathways', sa.JSON(), nullable=True),
    sa.Column('regional_demand', sa.JSON(), nullable=True),
    sa.Column('suitable_for', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qp_sector_active', 'qualification_packs', ['sector', 'is_active'], unique=False)
    op.create_index(op.f('ix_qualification_packs_is_active'), 'qualification_packs', ['is_active'], unique=False)
    op.create_index(op.f('ix_qualification_packs_qp_code'), 'qualification_packs', ['qp_code'], unique=True)
    op.create_index(op.f('ix_qualification_packs_sector'), 'qualification_packs', ['sector'], unique=False)
    op.create_table('training_centres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('centre_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('centre_type', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('official_portal', sa.String(length=512), nullable=True),
    sa.Column('affiliated_qp_codes', sa.JSON(), nullable=True),
    sa.Column('official_schemes', sa.JSON(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('next_batch_date', sa.String(length=20), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tc_district_active', 'training_centres', ['district', 'is_active'], unique=False)
    op.create_index('ix_tc_state_active', 'training_centres', ['state', 'is_active'], unique=False)
    op.create_index(op.f('ix_training_centres_centre_id'), 'training_centres', ['centre_id'], unique=True)
    op.create_index(op.f('ix_training_centres_centre_type'), 'training_centres', ['centre_type'], unique=False)
    op.create_index(op.f('ix_training_centres_district'), 'training_centres', ['district'], unique=False)
    op.create_index(op.f('ix_training_centres_is_active'), 'training_centres', ['is_active'], unique=False)
    op.create_index(op.f('ix_training_centres_state'), 'training_centres', ['state'], unique=False)
    op.create_table('nos_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qp_id', sa.Integer(), nullable=False),
    sa.Column('nos_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=100), nullable=True),
    sa.Column('related_skills', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qp_id'], ['qualification_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nos_modules_nos_code'), 'nos_modules', ['nos_code'], unique=False)
    op.create_index(op.f('ix_nos_modules_qp_id'), 'nos_modules', ['qp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nos_modules_qp_id'), table_name='nos_modules')
    op.drop_index(op.f('ix_nos_modules_nos_code'), table_name='nos_modules')
    op.drop_table('nos_modules')
    op.drop_index(op.f('ix_training_centres_state'), table_name='training_centres')
    op.drop_index(op.f('ix_training_centres_is_active'), table_name='training_centres')
    op.drop_index(op.f('ix_training_centres_district'), table_name='training_centres')
    op.drop_index(op.f('ix_training_centres_centre_type'), table_name='training_centres')
    op.drop_index(op.f('ix_training_centres_centre_id'), table_name='training_centres')
    op.drop_index('ix_tc_state_active', table_name='training_centres')
    op.drop_index('ix_tc_district_active', table_name='training_centres')
    op.drop_table('training_centres')
    op.drop_index(op.f('ix_qualification_packs_sector'), table_name='qualification_packs')
    op.drop_index(op.f('ix_qualification_packs_qp_code'), table_name='qualification_packs')
    op.drop_index(op.f('ix_qualification_packs_is_active'), table_name='qualification_packs')
    op.drop_index('ix_qp_sector_active', table_name='qualification_packs')
    op.drop_table('qualification_packs')
    op.drop_index(op.f('ix_government_schemes_scheme_code'), table_name='government_schemes')
    op.drop_index(op.f('ix_government_schemes_is_active'), table_name='government_schemes')
    op.drop_table('government_schemes')
    # ### end Alembic commands ###
